parameters:
    pim_catalog.family_variant.provider.entity_with_family_variant_attributes.class: Pim\Component\Catalog\FamilyVariant\EntityWithFamilyVariantAttributesProvider
    pim_catalog.family_variant.add_unique_attributes.class: Pim\Component\Catalog\FamilyVariant\AddUniqueAttributes
    pim_catalog.family_variant.change_family_variant_structure.class: Pim\Component\Catalog\FamilyVariant\ChangeFamilyVariantStructureOnDescendants

services:
    pim_catalog.family_variant.provider.entity_with_family_variant_attributes:
        class: '%pim_catalog.family_variant.provider.entity_with_family_variant_attributes.class%'

    pim_catalog.family_variant.add_unique_attributes:
        class: '%pim_catalog.family_variant.add_unique_attributes.class%'

    pim_catalog.family_variant.change_family_variant_structure:
        class: '%pim_catalog.family_variant.change_family_variant_structure.class%'
        arguments:
            - '@pim_catalog.repository.variant_product'
            - '@pim_catalog.repository.product_model'
            - '@pim_catalog.saver.product'
            - '@pim_catalog.saver.product_model'
