parameters:
    pim_catalog.tasklet.compute_product_models_descendants.class: Pim\Component\Catalog\Job\ComputeProductModelsDescendantsTasklet
    pim_catalog.tasklet.compute_variant_structure_changes.class: Pim\Component\Catalog\Job\ComputeVariantStructureChangesTasklet

    pim_catalog.compute_product_models_descendants.job_type: 'compute_product_models_descendants'
    pim_catalog.compute_product_models_descendants.job_name: 'compute_product_models_descendants'
    pim_catalog.compute_product_models_descendants.tasklet_name: 'compute_product_models_descendants'
    pim_catalog.compute_descendants.connector_name: 'compute descendants completeness'

    pim_catalog.compute_variant_structure_changes.job_type: 'compute_variant_structure_changes'
    pim_catalog.compute_variant_structure_changes.job_name: 'compute_variant_structure_changes'
    pim_catalog.compute_variant_structure_changes.tasklet_name: 'compute_product_models_descendants'
    pim_catalog.compute_variant_structure_changes.connector_name: 'compute variant structure changes'

services:
    pim_catalog.tasklet.compute_product_models_descendants:
        class: '%pim_catalog.tasklet.compute_product_models_descendants.class%'
        arguments:
            - '@pim_catalog.repository.product_model'
            - '@pim_catalog.saver.product_model_descendants'
        public: false

    pim_catalog.step.compute_product_models_descendants:
        class: '%pim_connector.step.tasklet.class%'
        arguments:
            - '%pim_catalog.compute_product_models_descendants.tasklet_name%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_catalog.tasklet.compute_product_models_descendants'
        public: false

    pim_catalog.job.compute_product_models_descendants:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - '%pim_catalog.compute_product_models_descendants.job_name%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@pim_catalog.step.compute_product_models_descendants'
        public: false
        tags:
            -
                name: akeneo_batch.job
                connector: '%pim_catalog.compute_descendants.connector_name%'
                type: '%pim_catalog.compute_product_models_descendants.job_type%'

    pim_catalog.tasklet.compute_variant_structure_changes:
        class: '%pim_catalog.tasklet.compute_variant_structure_changes.class%'
        arguments:
            - '@pim_catalog.repository.family_variant'
            - '@pim_catalog.family_variant.change_family_variant_structure'
        public: false

    pim_catalog.step.compute_variant_structure_changes:
        class: '%pim_connector.step.tasklet.class%'
        arguments:
            - '%pim_catalog.compute_variant_structure_changes.tasklet_name%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_catalog.tasklet.compute_variant_structure_changes'
        public: false

    pim_catalog.job.compute_variant_structure_changes:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - '%pim_catalog.compute_variant_structure_changes.job_name%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@pim_catalog.step.compute_variant_structure_changes'
        public: false
        tags:
            -
                name: akeneo_batch.job
                connector: '%pim_catalog.compute_variant_structure_changes.connector_name%'
                type: '%pim_catalog.compute_variant_structure_changes.job_type%'
